---
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Install nginx on Debian family
      apt:
        name: nginx
        state: present
        update_cache: yes

      tags:
       - apt_get            #you tag to enable you run just that task u can tag evrytin n jx call the tags to run specific task ex: ansible-playbook play.yaml --tag apt_get
      when: (ansible_processor_nproc > 2) or (ansible_os_family == "Debian")

    - name: Install httpd on RedHat family
      package:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: Start httpd daemon
      service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Create user serge
      user:
        name: serge
        comment: serge smith
        shell: /bin/bash

    - name: Create a group
      group:
        name: cloudteam
        state: present

    - name: Create index file
      file:
        path: /var/www/html/index.html
        state: touch
      register: file_output  
    - name: read data 
      debug:
        var: file_output.diff.before.path
    - name: Create a directory
      file:
        path: /tmp/os
        state: directory

    - name: Copy content to index
      copy:
        dest: file_output.diff.before.path
        content: 'This is created using Ansible'
