---
- hosts: wind 
  tasks:
    - name: create a directory 
      win_file:
        path: C:\Users\Administrator\Desktop\simon
        state: directory
    - name: download file online 
      win_get_url:
         dest: C:\Users\Administrator\Desktop\simon
         url: https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-6.9.3.tar.xz 

    - name: update all package
      win_updates: 
        category_names: '*'
        reboot: true